include:
  - board: seeeduino_xiao_ble
    shield: cosmotyl_left
    snippet: zmk-usb-logging
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: cosmotyl_right
